<?php
/**
 * SmsBulkStatus
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Infobip
 * @author   Infobip Support
 * @link     https://www.infobip.com
 */

/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace Infobip\Model;

use \Infobip\ObjectSerializer;

/**
 * SmsBulkStatus Class Doc Comment
 *
 * @category Class
 * @package  Infobip
 * @author   Infobip Support
 * @link     https://www.infobip.com
 */
class SmsBulkStatus
{
    /**
     * Possible values of this enum
     */
    const PENDING = 'PENDING';
    const PAUSED = 'PAUSED';
    const PROCESSING = 'PROCESSING';
    const CANCELED = 'CANCELED';
    const FINISHED = 'FINISHED';
    const FAILED = 'FAILED';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::PAUSED,
            self::PROCESSING,
            self::CANCELED,
            self::FINISHED,
            self::FAILED,
        ];
    }
}
