<?php
/**
 * WhatsAppAddressType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Infobip
 * @author   Infobip Support
 * @link     https://www.infobip.com
 */

/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace Infobip\Model;

use Infobip\ObjectSerializer;

/**
 * WhatsAppAddressType Class Doc Comment
 *
 * @category Class
 * @description Type of the address. Can be &#x60;HOME&#x60; or &#x60;WORK&#x60;.
 * @package  Infobip
 * @author   Infobip Support
 * @link     https://www.infobip.com
 */
class WhatsAppAddressType
{
    /**
     * Possible values of this enum
     */
    public const HOME = 'HOME';
    public const WORK = 'WORK';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::HOME,
            self::WORK,
        ];
    }
}
